# Conda metadata description

package:
  name: kbmtl
  version: "0.1.0"

source:
  url: https://github.com/patterja/kbmtl/archive/v0.1.0.tar.gz
  sha256: db092ab6e750b07f122a52ea3f02794c6700d16d7682b951ec3d896d08b57e6c
  #git_url: https://github.com/patterja/kbmtl

build:
  rpaths:
    - lib/
    - lib/R/lib/
  script: R CMD INSTALL . 

requirements:
  build:
    - r-base

  run:
    - r-base

test:
  commands:

about:
  home: https://github.com/patterja/kbmtl
  summary: Kernalized Baysian Multi-task Transfer Learning from breast cancer cell lines
